version: '3'
services:
  # mysql
  mysql:
    container_name: "flask-db"
    image: "mysql:5.7"
    volumes:
      #- ./mysql:/var/lib/mysql
      - ./mysql/import:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: python
      MYSQL_PASSWORD: python
      MYSQL_DATABASE: sample
  
  # flask
  flask:
    container_name: "flask"
    build: ./flask/
    ports:
      - "5000:5000"
    depends_on:
      - mysql